openapi: 3.0.2
info:
  title: Tournament microservice specification
  version: 1.0.0
  description: Specification for tournament microservice
  contact:
    name: AimCup
    email: aimcupdev@gmail.com

paths:
  /tournaments:
    $ref: './paths/tournaments/tournaments.yaml'
  /tournaments/{tournamentId}:
    $ref: './paths/tournaments/tournament.yaml'
  /tournaments/{tournamentId}/info:
    $ref: './paths/tournaments/tournament-info.yaml'
  /tourmaments/{tournamentId}/participate:
    $ref: './paths/tournaments/participate.yaml'
  /matches:
    $ref: './paths/matches/matches.yaml'