openapi: 3.0.2
info:
  title: Sample OpenAPI Specification for Spring Boot API
  version: 1.0.0
  description: A sample Spring Boot API using OpenAPI specification
  contact:
    name: AimCup
    email: aimcupdev@gmail.com
tags:
  - name: Sample-OpenApi
    description: Sample-OpenApi

paths:
  /examples:
    $ref: './paths/example/example.yaml'
