openapi: 3.0.2
info:
  title: Tournament microservice specification
  version: 1.0.0
  description: Specification for tournament microservice
  contact:
    name: AimCup
    email: aimcupdev@gmail.com

paths:
  /tournament:
    $ref: './paths/tournament/create-tournament-request.yaml'
  /tournament/{tournamentId}:
    $ref: './paths/tournament/tournament-by-id.yaml'
  /tourmament/{tournamentId}/participate:
    $ref: './paths/tournament/participate.yaml'
  /tournaments:
    $ref: './paths/tournaments/tournaments.yaml'