version: '3.8'

services:
  tournament-microservice:
    build:
      context: ../..
      dockerfile: docker/stg/stg-build-deploy.Dockerfile
    ports:
      - "8201:8201"
    environment:
      - DB_STG_ADDRESS=${DB_STG_ADDRESS}
      - DB_STG_USER=${DB_STG_USER}
      - DB_STG_PASSWORD=${DB_STG_PASSWORD}
      - EUREKA_STG=${EUREKA_STG}
      - STG_OSU_API_NAME_ISSUER_ID=${STG_OSU_API_NAME_ISSUER_ID}
      - STG_OSU_API_NAME_ID=${STG_OSU_API_NAME_ID}
      - STG_OSU_API_CLIENT_ID=${STG_OSU_API_CLIENT_ID}
      - STG_OSU_API_CLIENT_SECRET=${STG_OSU_API_CLIENT_SECRET}
      - STG_OSU_API_JWK_SET_URI=${STG_OSU_API_JWK_SET_URI}

networks:
  default:
    external: true
    name: aimcup-network