version: '3.8'

services:
  tournament-microservice:
    build:
      context: ../..
      dockerfile: docker/stg/stg-build-deploy.Dockerfile
    ports:
      - "8201:8201"
    environment:
      - DB_STG_ADDRESS=${DB_STG_ADDRESS}
      - DB_STG_USER=${DB_STG_USER}
      - DB_STG_PASSWORD=${DB_STG_PASSWORD}
      - EUREKA_STG=${EUREKA_STG}
      - STG_KEYCLOAK_NAME_ISSUER=${STG_KEYCLOAK_NAME_ISSUER}
      - STG_KEYCLOAK_CLIENT_NAME=${STG_KEYCLOAK_CLIENT_NAME}
      - STG_KEYCLOAK_CLIENT_ID=${STG_KEYCLOAK_CLIENT_ID}
      - STG_KEYCLOAK_CLIENT_SECRET=${STG_KEYCLOAK_CLIENT_SECRET}
      - STG_KEYCLOAK_JWK_SET_URI=${STG_KEYCLOAK_JWK_SET_URI}

networks:
  default:
    external: true
    name: aimcup-network