version: '3.8'

services:
  tournament-microservice:
    build:
      context: ../..
      dockerfile: stg-build-deploy.Dockerfile
    ports:
      - "8201:8201"

networks:
  default:
    external: true
    name: aimcup-network