eureka:
  client:
    enabled: false
server:
  servlet:
    context-path: /tournament
  port: 8081
  error:
    include-message: always
spring:
  application:
    name: tournament-microservice
  datasource:
    url: jdbc:postgresql://localhost:5501/tournament
    username: testUser
    password: testPassword
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10
      idle-timeout: 5000
      max-lifetime: 1000
      auto-commit: true
  flyway:
    locations: classpath:db/migration
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        provider:
          aimcup:
            issuer-uri: http://localhost:8080/realms/aimcup
        registration:
          aimcup:
            provider: aimcup
            client-name: aimcup
            client-id: aimcup
            client-secret: MUSDaD5wr0p06E8rwlVXkteKagnr29lU
            scope: profile,openid,offline_access