spring:
  application:
    name: TOURNAMENT-SERVICE
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka
server:
  servlet:
    context-path: /api/tournament
  port: 8080
