eureka:
  client:
    service-url:
      defaultZone: http://172.18.0.1:8762/eureka
server:
  servlet:
    context-path: /tournament
  port: 8201
  error:
    include-message: always
spring:
  application:
    name: tournament-microservice
  datasource:
    url: jdbc:postgresql://172.18.0.1:5501/tournament
    username: tournament
    password: ${TOURNAMENT_DB_STG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10
      idle-timeout: 5000
      max-lifetime: 1000
      auto-commit: true
  flyway:
    locations: classpath:db/migration
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        provider:
          aimcup:
            issuer-uri: https://keycloak-stg.aimcup.xyz/realms/aimcup-realm
            jwk-set-uri: https://keycloak-stg.aimcup.xyz/realms/aimcup-realm/protocol/openid-connect/certs
            authorization-uri: https://keycloak-stg.aimcup.xyz/realms/aimcup-realm/protocol/openid-connect/auth
            token-uri: https://keycloak-stg.aimcup.xyz/realms/aimcup-realm/protocol/openid-connect/token
            user-info-uri: https://keycloak-stg.aimcup.xyz/realms/aimcup-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          aimcup:
            provider: aimcup
            client-name: aimcup
            client-id: aimcup
            client-secret: MUSDaD5wr0p06E8rwlVXkteKagnr29lU
            scope: profile,openid,offline_access
            redirect-uri: https://api-stg.aimcup.xyz/tournament/keycloak-test
