version: '3.8'

services:
  tournament-microservice:
    build:
      context: ../..
      dockerfile: docker/prd/prd-build-deploy.Dockerfile
    ports:
      - "8101:8101"
    environment:
      - TOURNAMENT_DB_PRD_PASSWORD=${POSTGRES_PASSWORD}

networks:
  default:
    external: true
    name: aimcup-network