name: Deploy to Staging

on:
  pull_request:
    types:
      - closed
    branches:
      - stage
  workflow_dispatch:
    branches: [ "stage" ]

jobs:
  build:
    runs-on:
      group: Default
    steps:
      - uses: actions/checkout@v3
      - name: Run microservice db (if needed)
        run: |
          docker-compose -f docker/stg/stg-run-database-job.yml up -d --build
        env:
          DB_STG_USER: ${{ secrets.DB_STG_USER }}"
          DB_STG_PASSWORD: ${{ secrets.DB_STG_PASSWORD }}"
      - name: Build and deploy the Docker image
        run: |
          docker-compose -f docker/stg/stg-build-deploy-job.yml up -d --build
        env:
          DB_STG_ADDRESS: ${{ secrets.DB_STG_ADDRESS }}"
          DB_STG_USER: ${{ secrets.DB_STG_USER }}"
          DB_STG_PASSWORD: ${{ secrets.DB_STG_PASSWORD }}"
          EUREKA_STG: ${{ secrets.EUREKA_STG }}"
          STG_OSU_API_NAME_ISSUER_ID: ${{ secrets.STG_OSU_API_NAME_ISSUER_ID }}"
          STG_OSU_API_NAME_ID: ${{ secrets.STG_OSU_API_NAME_ID }}"
          STG_OSU_API_CLIENT_ID: ${{ secrets.STG_OSU_API_CLIENT_ID }}"
          STG_OSU_API_CLIENT_SECRET: ${{ secrets.STG_OSU_API_CLIENT_SECRET }}"
          STG_OSU_API_JWK_SET_URI: ${{ secrets.STG_OSU_API_JWK_SET_URI }}"