name: build-check

on:
  push:
    branches: [ "stage" ]
  pull_request:
    branches: [ "stage" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Maven Verify
        run: mvn --batch-mode --update-snapshots verify
      - name: Upload coverage
          uses: actions/upload-artifact@v2
          with:
            name: test-case reports
            path: aimcup/build/github
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    needs: [ build ]
    steps:
      - name: download reports
        uses: actions/download-artifact@v2
        with:
          name: test-case reports
          path: aimcup/build/github
      - name: Display structure of downloaded files
        run: ls -R
      - uses: actions/checkout@v2
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: 'aimcup/build/github/coverage.xml'